services:
  app:
    build:
      context: ./php
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - proxy

  web:
    image: nginx:stable
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - proxy

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - proxy

  node:
    image: node:20
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: ["tail", "-f", "/dev/null"]
    networks:
      - proxy

networks:
  proxy:
    external: true
